"""initial schema

Revision ID: 44f836835253
Revises: 
Create Date: 2026-08-19 23:27:17.940091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44f836835253'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('who_it_may_help', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('optional_documents', sa.JSON(), nullable=True),
    sa.Column('preparation_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_steps', sa.JSON(), nullable=True),
    sa.Column('availability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['anonymous_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_scheme_id'), 'plans', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_plans_session_id'), 'plans', ['session_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('income_band', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clean_cooking', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('situations', sa.JSON(), nullable=True),
    sa.Column('education_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enrolled', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('landholding', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('training_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('planning_business', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['anonymous_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_session_id'), 'profiles', ['session_id'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_scheme_id'), 'rules', ['scheme_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_table('reference_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['anonymous_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_requests_plan_id'), 'reference_requests', ['plan_id'], unique=False)
    op.create_index(op.f('ix_reference_requests_reference_code'), 'reference_requests', ['reference_code'], unique=True)
    op.create_index(op.f('ix_reference_requests_scheme_id'), 'reference_requests', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_reference_requests_session_id'), 'reference_requests', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_requests_session_id'), table_name='reference_requests')
    op.drop_index(op.f('ix_reference_requests_scheme_id'), table_name='reference_requests')
    op.drop_index(op.f('ix_reference_requests_reference_code'), table_name='reference_requests')
    op.drop_index(op.f('ix_reference_requests_plan_id'), table_name='reference_requests')
    op.drop_table('reference_requests')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_rules_scheme_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_profiles_session_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_plans_session_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_scheme_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('schemes')
    op.drop_table('anonymous_sessions')
    # ### end Alembic commands ###
